[variables]
NODE_VERSION = "20"

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx prisma db push && node prisma/seed-super-admin.js && npm start"
